### ISSUE TITLE
Security vulnerability in the function getParameterByName(name, url)

### ISSUE THREAD

**Issue by stephangrass** [giantmonkey/gomus-public-iframe-example#2]
With the current function getParameterByName(name, url), it's possible to embed arbitrary pages via an iFrame. This is not secure. Keywords: Clickjacking, Mixed Content, Phishing.

It would be advantageous to adjust the function so that the resulting URL begins with a domain ending in ".gomus.de". Here's an example:

```
function getParameterByName(name, url) {
    if (!url) {
        url = window.location.href;
    }
    name = name.replace(/[\[\]]/g, "\\$&");
    var regex = new RegExp("[?&]" + name + "(=([^&#]*)|&|#|$)");
    var results = regex.exec(url);

    if (!results) return null;
    if (!results[2]) return '';

    var resultUrl = decodeURIComponent(results[2].replace(/\+/g, " "));
    var domainRegex = new RegExp("^https?://([a-z0-9-]+\\.)?gomus\\.de");

    if (!domainRegex.test(resultUrl)) {
        return null;
    }
    
    return resultUrl;
}
```

**Comment by vollnhals** [comment]
Thanks for reporting the issue. We will investigate and then update the snippet on the project page.

**Comment by vollnhals** [comment]
@stephangrass We see two issues with the domainRegex as presented.

- gomus is not restricted to gomus.de . We also use .cloud, .lu and .at domains, and probably others in the future.
- What about https://gomus.de.shady-hackers.ru ? Currently that would be considered valid.

**Comment by stephangrass** [comment]
You are right!
We can try something like this:

```
function getParameterByName(name, url) {
    if (!url) {
        url = window.location.href;
    }
    name = name.replace(/[\[\]]/g, "\\$&");
    var regex = new RegExp("[?&]" + name + "(=([^&#]*)|&|#|$)");
    var results = regex.exec(url);

    if (!results) return null;
    if (!results[2]) return '';

    var resultUrl = decodeURIComponent(results[2].replace(/\+/g, " "));
    
    var urlObject = new URL(resultUrl);
    var domainRegex = new RegExp("^([a-z0-9-]+\\.)?gomus\\.(de|cloud|lu|at)$");

    if (!domainRegex.test(urlObject.hostname)) {
        return null; // or an appropriate error value.
    }
    
    return resultUrl;
}
```

**Comment by vollnhals** [comment]
@stephangrass Thank you for your contribution. Your changes have been merged into the README.
